#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-oss-pf-policy-dist.name" . }}-sa
  labels:
    app: {{ template "eric-oss-pf-policy-dist.name" . }}
    chart: {{ template "eric-oss-pf-policy-dist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- include "eric-oss-pf-policy-dist.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-pf-policy-dist.eric-product-info" .| nindent 4 }}
automountServiceAccountToken: false