apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-oss-pf-policy-dist-configmap.name" . }}
  labels:
    app: {{ template "eric-oss-pf-policy-dist-configmap.name" . }}
  {{- include "eric-oss-pf-policy-dist.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-oss-pf-policy-dist.eric-product-info" .| nindent 4 }}
{{- with .Files.Glob "resources/config/*store" }}
binaryData:
{{- range $path, $bytes := . }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc | quote }}
{{- end }}
{{- end }}
data:
{{ tpl (.Files.Glob "resources/config/config.json").AsConfig . | indent 2 }}
